FROM node:20-bullseye-slim AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y git openssl libssl-dev

RUN git clone --depth 1 https://github.com/calcom/cal.com.git .
RUN yarn install --frozen-lockfile
RUN yarn build

FROM node:20-bullseye-slim
WORKDIR /app
COPY --from=builder /app .

ENV NEXTAUTH_SECRET=changeme
ENV DATABASE_URL=file:./db.sqlite

EXPOSE 3000
CMD ["yarn", "start"]
